-- Version 2020

Prompt ***** jugadores	1

CREATE TABLE jugadores 
(
  nickname VARCHAR2(15),
  nombre VARCHAR2(15) not null,
  apellido1 varchar2(15) not null,
  apellido2 varchar2(15),
  constraint pk_nickname_jugadores primary key (nickname)
);

Prompt ******  tabla fichas	2

CREATE TABLE fichas
(
	id_ficha number(2) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	sigla char(1) NOT NULL,
	nombre varchar2(7) not null,
	constraint pk_id_ficha_fichas primary key (id_ficha)
);

Prompt ******  coordenadas_tablero	3

CREATE TABLE coordenadas_tablero
(
	id_cord_tab number GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	coordenada char(2) not null,
	constraint pk_id_cord_tab_coordenadas_tablero primary key (id_cord_tab)
);

Prompt ******  partidas	4

create table partidas
(
	id_partida number GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	nickname1 varchar2(15) not null,
	nickname2 varchar2(15) not null,
	fecha_inicio date default sysdate,
	fecha_fin date,
	resultado varchar2(60),
	constraint pk_id_partida_partidas primary key (id_partida),
	constraint fk_nickname1_partidas foreign key (nickname1) references jugadores (nickname),
	constraint fk_nickname2_partidas foreign key (nickname2) references jugadores (nickname)
	-- constraint ck_fecha_inicio_partidas CHECK (fecha_inicio >= sysdate),
	-- constraint ck_fecha_fin_partidas check (fecha_fin >= sysdate)
);


Prompt ******  estado_partidas	5

create table estado_partidas
(
	id_estado_partida number GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	id_cord_tab number not null,
	id_partida number not null,
	id_ficha number(2),
	constraint pk_id_estado_partida_fichas primary key (id_estado_partida),
	constraint fk_id_cord_tab_partida_fichas foreign key (id_cord_tab) references coordenadas_tablero (id_cord_tab),
	constraint pk_id_partida_estado_partidas foreign key (id_partida) references partidas (id_partida),
	constraint pk_id_ficha_estado_partidas foreign key (id_ficha) references fichas (id_ficha)
);

Prompt ******  movimientos	6

create table movimientos
(
	id_movimiento number GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	movimiento number(3) not null;
	id_partida number not null,
	id_ficha number(2) not null,
	pos_inicial number not null,
	pos_final number not null,
	notacion varchar2(12) not null,
	constraint pk_iid_movimiento_movimientos primary key (id_movimiento),
	constraint fk_id_partida_movimientos foreign key (id_partida) references partidas (id_partida),
	constraint fk_id_ficha_movimientos foreign key (id_ficha) references fichas (id_ficha),
	constraint fk_pos_inicial_movimientos foreign key (pos_inicial) references coordenadas_tablero (id_cord_tab),
	constraint fk_pos_final_movimientos foreign key (pos_final) references coordenadas_tablero (id_cord_tab)
);

Prompt ******  movimientos	7

create table partida_activa
(
	id_partida number not null,
	constraint pk_id_partida_partida_activa foreign key (id_partida) references partidas (id_partida)
);

column table_name format a30
column tname format a30

select * from cat;
