Prompt ***** jugadores

insert into jugadores values ('MML','Mario','Martinez','Lanuza');
insert into jugadores values ('RRM','Roger','Retana','Mcnally');
insert into jugadores values ('FG','Fernanda','Granados',null);

Prompt ******  partidas

insert into partidas (nickname1, nickname2) values ('MML','RRM');

insert into partidas (nickname1, nickname2) values ('MML','FG');

insert into movimientos (id_partida, id_ficha, pos_inicial, pos_final, notacion) values (1,6,12,28,'d2d4');
insert into movimientos (id_partida, id_ficha, pos_inicial, pos_final, notacion) values (1,12,53,37,'e7e5');
insert into movimientos (id_partida, id_ficha, pos_inicial, pos_final, notacion) values (1,6,28,37,'d4e5xp');

alter table movimientos
modify id_ficha number(2);

alter table estado_partidas
modify id_ficha number(2) null;

alter table partidas
modify id_partida number generated by default on null as identity;

alter table partidas
modify id_partida number GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1;

update estado_partidas
set id_ficha = null
where id_cord_tab = 12 and id_partida = 1;
update estado_partidas
set id_ficha = 6
where id_cord_tab = 28 and id_partida = 1;